site_name: Documentação IBLicita
theme:
  name: material
  language: pt-BR
  palette:
    # Configuração para o Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Configuração para o Modo Escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

# Se você quiser que o nome do projeto no topo também seja laranja:
extra_css:
  - stylesheets/extra.css
nav:
  - Início: index.md
  - Modulos:
      - Exemplo de HU: exemplo-hu.md