name: publish
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Instalar Dependências do Sistema (Obrigatório para o PDF)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

      - name: Instalar MkDocs e Plugins
        run: |
          pip install mkdocs-material mkdocs-with-pdf

      - name: Gerar Site e PDF
        run: mkdocs gh-deploy --force